### ISSUE TITLE
Examples do not reflect the change in prediction grid cell size

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/dsm#15]
At least in `dsm1, `dsm.var.movblk`,  `dsm.var.prop` but I suspect it crops up elsewhere...

```
 # Calculate the offset...
 off.set <- 444*1000*1000
```

.Rd for mexdolphins seems screwed up: format section does not clearly show data structure...

**Comment by erex** [comment]
### Two more hassles with the spotted dolphin vignette

Last sentence of Section 5 is incorrect (around line 317 in Rmd I think)
"Later in this document, we demonstrate fitting of a detection function with size as a covariate, but for now we stick to a simple model."

Similarly in Sect 6.3 you note that you are working with a sighting-level covariate when you include sea state in the detection function.  I think this is technically incorrect, because sea state is recorded at the segment level.  True, in the D7 project and in your data structure, beauford is in the observation layer, I suspect field workers are likely to record sea state at a level above the sighting-level.

It matters not to the analysis you are performing, and it helps you motivate the use of the HT-like estimator, but you might get emails from folks who pick you up on that.

**Comment by dill** [comment]
In order:

 * prediction grid cell size is fixed in the version of `dsm` on github, though this needs to go to CRAN.
 * I've removed the "format" section, which doesn't seem useful anyway and instead refrenced the vignette on the Distance website
 * removed the "later in this document..."
 * I'll leave the observation vs. segment layer bit as-is -- I suppose that Beaufort could be recorded either way depending on how the survey was conducted (I've seen examples of both) so I don't think that's too problematic.
